### ISSUE TITLE
Docker Health Check Fail

### ISSUE THREAD

**Issue by KodySalak** [gregtwallace/legocerthub#16]
When I'm using the container, I get an "unhealthy" status and here's the JSON from that section of my log.
```
"State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2023-07-11T04:12:43.527960695Z",
        "Health": {
            "FailingStreak": 8333,
            "Log": [
                {
                    "End": "2023-07-13T20:53:33.99440994-05:00",
                    "ExitCode": 1,
                    "Output": "Connecting to localhost:4050 (127.0.0.1:4050)\nwget: can't connect to remote host (127.0.0.1): Connection refused\n",
                    "Start": "2023-07-13T20:53:33.936330529-05:00"
                },
                {
                    "End": "2023-07-13T20:54:04.082318507-05:00",
                    "ExitCode": 1,
                    "Output": "Connecting to localhost:4050 (127.0.0.1:4050)\nwget: can't connect to remote host (127.0.0.1): Connection refused\n",
                    "Start": "2023-07-13T20:54:03.998428635-05:00"
                },
                {
                    "End": "2023-07-13T20:54:34.14414351-05:00",
                    "ExitCode": 1,
                    "Output": "Connecting to localhost:4050 (127.0.0.1:4050)\nwget: can't connect to remote host (127.0.0.1): Connection refused\n",
                    "Start": "2023-07-13T20:54:34.086021934-05:00"
                },
                {
                    "End": "2023-07-13T20:55:04.210004717-05:00",
                    "ExitCode": 1,
                    "Output": "Connecting to localhost:4050 (127.0.0.1:4050)\nwget: can't connect to remote host (127.0.0.1): Connection refused\n",
                    "Start": "2023-07-13T20:55:04.14806-05:00"
                },
                {
                    "End": "2023-07-13T20:55:34.278564661-05:00",
                    "ExitCode": 1,
                    "Output": "Connecting to localhost:4050 (127.0.0.1:4050)\nwget: can't connect to remote host (127.0.0.1): Connection refused\n",
                    "Start": "2023-07-13T20:55:34.213018561-05:00"
                }
            ],
            "Status": "unhealthy"
        }
```

my compose:
```
version: "3"

services:
  legocerthub:
    container_name: legocerthub
    image: ghcr.io/gregtwallace/legocerthub:latest
    restart: unless-stopped
    ports:
      - int.ern.al.IP:4055:4055   # server interface (https)
    volumes:
      - /opt/containers/certhub/:/app/data
      - /opt/containers/certhub/config.yaml:/app/config.yaml
```
(I brought my config over from the linux version initially released (0.0.1))

I'm trying to figure out what's going on - whether it's the container configuration or networking...

Is there a verbose logging mode I can turn on to get absolutely every log possible that can help me troubleshoot?

**Comment by gregtwallace** [comment]
Did you change the http(s) ports in your config?  You have to leave the ports as the default if you’re using the container.

**Comment by KodySalak** [comment]
I did not... config is below (with comments removed)
```
config_version: 0

hostname: 'cer.mydomain.com'

bind_address: ''
https_port: 4055
http_port: 4050

enable_http_redirect: false

# Server logging level
log_level: 'debug'

# Should the server also host the frontend?
serve_frontend: true

cors_permitted_origins: []

private_key_name: CERT-Certhub
certificate_name: Certhub

# Development mode
dev_mode: false

# Update checking functionality
updater:
  auto_check: true
  channel: beta

# Orders configuration
orders:
  # settings for automatic ordering
  auto_order_enable: true
  valid_remaining_days_threshold: 12
  refresh_time_hour: 21
  refresh_time_minute: 12

# Challenge Providers
challenges:
  dns_checker:
    skip_check_wait_seconds: 40
    dns_services:
      - primary_ip: 1.1.1.1
        secondary_ip: 1.0.0.1
      - primary_ip: 9.9.9.9
        secondary_ip: 149.112.112.112
      - primary_ip: 8.8.8.8
        secondary_ip: 8.8.4.4
  providers:
    # http-01 internal server
    http_01_internal:
      enable: false
      port: 4060
    dns_01_manual:
      enable: false
      environment:
        - 'MY_EXPORT_VAR=some_value'
        - 'ANOTHER_EXPORT_ENV=another_value'
      create_script: ./scripts/create-dns.sh
      delete_script: ./scripts/delete-dns.sh
    dns_01_acme_dns:
      enable: false
      acme_dns_address: http://localhost:8880
      resources:
        - real_domain: secure-server.example.com
          # the matching information about the acme-dns domain
          # that will be updated
          full_domain: ee29dc47-aaaa-aaaa-aaaa-aaaaaaaaaaaa.decoy.dummy.com
          username: ee29dc47-bbbb-bbbb-bbbb-bbbbbbbbbbbb
          password: QWDP...b2Mg
    dns_01_acme_sh:
      enable: false
      acme_sh_path: ./scripts/acme.sh
      environment:
        - 'MY_EXPORT_VAR=some_value'
        - 'ANOTHER_EXPORT_ENV=another_value'
      dns_hook: dns_cf
    # dns-01 via LeGo Cloudflare integration
    dns_01_cloudflare:
      enable: true
      accounts:
        - email: my@realemail.com
          global_api_key: APIKEY
      api_tokens:
        - api_token: APIKEY
```
