### ISSUE TITLE
Docker & Docker Compose

### ISSUE THREAD

**Issue by gummipunkt** [gregtwallace/legocerthub#4]
Hi,

I've tried to use Docker / Docker Compose. My docker-compose.yml 

```
version: '3.3'

services:
  legocerthub:
    image: ghcr.io/gregtwallace/legocerthub:latest
    container_name: legocerthub
    volumes:
      - /opt/legocerthub/data:/app/data
    ports:
      - 4050:4050  # <Host Port>:<Container Port>
      - 4055:4055
      - 4060:4060
    restart: always
```

Works. I can connect to the login page. But then I need credentials which I don't have. Also, it's not clear for me, how to get the config.yml because it's not generated during the first run. Could you provide a sample one?
